sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-take-out0622
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
   appid: wx042bb4b41f9cea22
   secret: a5e92589ffddcfb06158d24a27821350
